### ISSUE TITLE
TODO: trivia

### ISSUE THREAD

**Issue by deryuzhkoyui** [Hainee-tyan/Translator#1]
1. [x] Request for JSON translation can return errors - handle it.
2. [x] If there is no translation in Yandex.Dictionary, try Yandex.Translation.
   <br> ~~There is only english-to-russian translations now. Define language of word dynamically and translate to russian (or to english if word is russian).~~
3. [x] If word consists of latin letters - translate en-ru, if cyrillic - translate ru-en.
4. [x] Selection + right shift = pop up translation (use Yandex.Translation, cause there can be sentences).
   <br>~~Add ability to choose language of word in panel (drop-down list in right of header) + dynamically change width of panel.~~
5. [ ] Add copy of translation function to clipboard.
6. [ ] Localization.
